version: '3.7'
services:
  postgres:
    image: library/postgres:9-alpine
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: orders
  adminer:
    image: adminer
    ports:
    - 8085:8080